from setuptools import setup, find_packages

setup(
    name="moviepy-layout",
    version="0.1.1",
    packages=find_packages(),
    install_requires=open("requirements.txt").read().splitlines(),
    author="Kmm Hanan",
    author_email="hanan@kmmhanan.com",
    description="Composable layout primitives for MoviePy: RGBA gradients, asset modes, and styled containers",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/kmmhanan/moviepy-layout",
    project_urls={
        "Documentation": "https://github.com/kmmhanan/moviepy-layout#readme",
        "Source": "https://github.com/kmmhanan/moviepy-layout",
        "Tracker": "https://github.com/kmmhanan/moviepy-layout/issues",
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Multimedia :: Video",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
    ],
    keywords=[
        "moviepy",
        "video editing",
        "layout engine",
        "RGBA",
        "gradient",
        "asset mode",
        "composable",
        "python video",
        "flutter-style",
        "css-inspired",
        "media automation",
    ],
    python_requires=">=3.8",
)
